spring:
  data:
    mongodb:
      username: admin
      password: password
      database: mongodemo
      authentication-database: admin
      uri: mongodb://admin:password@localhost:27017/mongodemo?authSource=admin
